name: Publish 'latest' image

on:
  release:
    types:
      - "created"

jobs:
  cd:
    uses: decentraland/platform-actions/.github/workflows/apps-docker-release.yml@main
    with:
      service-name: comms-scraper
      deployment-environment: prd
    secrets: inherit
